judge/urls.py
from django.conf.urls.defaults import *

from oj.judge.models import Judge


urlpatterns = patterns('oj.judge.views',

	(r'^$', 'judge_list'),

	(r'^(?P<object_id>\d+)/$', 'judge_detail'),

	(r'^(?P<object_id>\d+)/print_ass/$', 'judge_print_ass'),

	(r'^(?P<object_id>\d+)/print_exp/$', 'judge_print_exp'),

	(r'^(?P<object_id>\d+)/rejudge/$', 'judge_rejudge'),

)

urls.py
from django.conf.urls.defaults import *
from django.contrib import admin
from django.conf import settings
admin.autodiscover()

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^oj/', include('oj.foo.urls')),

    # Uncomment the admin/doc line below and add 'django.contrib.admindocs' 
    # to INSTALLED_APPS to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
	(r'^admin/(.*)', admin.site.root),
	(r'^images/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_PATH}),
	(r'^problem/', include('oj.problem.urls')),
	(r'^$', 'oj.volume.views.index'),
	(r'^volume/', include('oj.volume.urls')),
	(r'^users/', include('oj.userprofile.urls')),
	(r'^judge/', include('oj.judge.urls')),
	(r'^contest/', include('oj.contest.urls')),
)

judge/models.py
#coding=utf-8
from django.db import models
from django.forms import ModelForm
from django.contrib.auth.models import User
from oj.contest.models import Contest
from oj.problem.models import Problem

# Create your models here.

LANGUAGE_CHOICES = (
	('c++', 'C++(GNU C++ 4.0)'),
	('c', 'C(GNU C 4.0)'),
	('python', 'Python (Python 2.4)'),
	('java', 'Java (Not supported yet)'),
)

RESULT_CHOICES = (
	('AC', '正确'),
	('TLE', '超出时间'),
	('MLE', '超出内存'),
	('RE', '运行错误'),
	('CE', '编译错误'),
	('WA', '答案错误'),
	('PE', '格式错误'),
	('OT', '时间结束'),
	('RV', '违规'),
	('WAIT', '等待测试'),
	('TESTING','正在测试'),
	('JE', '判题系统内部错误'),
)

class Judge(models.Model):
	user = models.ForeignKey(User, verbose_name = u'用户')
	problem = models.ForeignKey(Problem, verbose_name = u'判题')
	language = models.CharField('程序设计语言', default= 'c++',max_length = 100, choices=LANGUAGE_CHOICES)
	sourcecode = models.TextField('源代码')
	submittime = models.DateTimeField('提交时间')
	result = models.CharField('判题结果',default = 'WAIT', max_length = 100, blank = True, choices = RESULT_CHOICES)
	result_detail = models.TextField('判题结果详细描述', blank = True)
	incontest = models.ForeignKey(Contest, verbose_name = u'比赛', null = True, blank=True)
	
	def __unicode__(self):
		return u'%6d %10s %10s %8s %15s %5s' % (self.id, self.user, self.problem, self.language, self.submittime, self.result)

	class Admin:
		list_filter = ('user','submittime',u'result')
		list_display = ('id', u'user', u'problem', 'language', u'result')

	class Meta:
		ordering = ['-id']
		verbose_name = verbose_name_plural = u'判题'

class JudgeForm(ModelForm):
	class Meta:
		model = Judge

judge/views.py
#coding=utf-8
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response
from oj.judge.models import Judge
from oj.problem.models import Problem
from oj.volume.models import ProblemVolume
from django import forms
from django.template import RequestContext

def judge_print_exp(request, object_id):
	judge = Judge.objects.get(id__exact = object_id)
	if request.user.is_anonymous() or ( not request.user.is_superuser and judge.user != request.user):
		errors = {'Permission not allowed, please log in as the author':''}
		return render_to_response('errors.html', {'errors':errors})
	userprofile = request.user.get_profile()
	c=RequestContext(request, {'object':judge,'userprofile':userprofile})
	return render_to_response('judge/judge_print_exp.html', c)

def judge_print_ass(request, object_id):
	judge = Judge.objects.get(id__exact = object_id)
	if request.user.is_anonymous() or ( not request.user.is_superuser and judge.user != request.user):
		errors = {'Permission not allowed, please log in as the author':''}
		return render_to_response('errors.html', {'errors':errors})
	userprofile = request.user.get_profile()
	c=RequestContext(request, {'object':judge,'userprofile':userprofile})
	return render_to_response('judge/judge_print_ass.html', c)

def judge_detail(request, object_id):
	judge = Judge.objects.get(id__exact = object_id)
	if ((not request.user.is_anonymous()) and judge.user == request.user)or request.user.is_staff:
		return render_to_response('judge/judge_detail.html', RequestContext(request, {'judge':judge}))
	else:
		errors = {'Permission not allowed, please log in as the author':''}
		return render_to_response('errors.html', {'errors':errors})


def judge_rejudge(request, object_id):
	judge = Judge.objects.get(id__exact = object_id)
	if not request.user.is_superuser and judge.user != request.user:
		errors = {'Permission not allowed, please log in as the author':''}
		return render_to_response('errors.html', {'errors':errors})
	judge.result = "WAIT"
	judge.save()
	return HttpResponseRedirect('/judge/%s/' %object_id)
#    return render_to_response('judge/judge_detail.html', RequestContext(request, {'object': judge}))

def judge_list(request):
	user = request.user
	if user.is_anonymous():
		return render_to_response('userprofile/login.html', {'user':user})
	userprofile = user.get_profile()
	filter_option = {}
	option = {}
	page = int(request.GET.get('page', '1'))

	for filter_name in ['user', 'problem', 'result', 'language', 'contest' ]:
		filter_value = request.GET.get(filter_name)
	if filter_value:
		filter_option[filter_name+'__exact'] = filter_value
		option[filter_name] = filter_value


	alljudges = Judge.objects.filter(**filter_option)
	pages = (alljudges.count()-1)/20+1
	judges = alljudges[20*(page-1):20*page]

	optionurl = "&".join( ["%s=%s"%(k, v) for (k, v) in option.items()] )
	c=RequestContext(request, 
		   {'user':user,'userprofile':userprofile,'object_list':judges, 'is_paginated':True, 'has_previous':(page > 1), 'has_next':(page<pages), 'page':page, 'pages':pages, 
			'next'    :optionurl+'&page=%s' % (page+1), 
			'previous':optionurl+'&page=%s' % (page-1)})
	return render_to_response('judge/judge_list.html',c )

templates/judge/judge_detail.html
{% extends "base.html" %}
{% block title %}
判题详细结果 - {{judge.id}}
{% endblock %}

{% block content %}

<table border = '1'>
  <tr>
    <td>判题编号</td><td> {{judge.id}}</td>
  </tr>
  <tr>
    <td>用户</td><td><a 
href="/users/{{judge.user.id}}/">{{judge.user}} {{judge.user.get_profile.name}}</a></td>
  </tr>
  <tr>
    <td>问题</td><td><a href="/problem/{{judge.problem.id}}/">{{judge.problem}}</a></td>
  </tr>
  <tr>
    <td>语言</td><td> {{judge.get_language_display}}</td>
  </tr>
  <tr>
    <td>提交时间</td><td>{{judge.submittime}}</td>
  </tr>
  <tr>
    <td>结果</td><td>{{judge.get_result_display}}</td>
  </tr>

<tr>
  <td>比赛</td><td>{{judge.incontest}}</td>
</tr>

  <tr>
<td>详细结果</td><td><pre>{{judge.result_detail}}</pre></td>
  </tr>
  <tr>
    <td>源代码</td>
    <td><pre>{%ifequal user judge.user%}{{judge.sourcecode|escape}}{% else %}{% if user.is_superuser %}{{ judge.sourcecode|escape }} {% else %} 无权查看 {% endif %} {% endifequal%}</pre>
    </td>
  </tr>
</table>

<table>
  <tr>
    <td><a href="./print_exp/">实验打印视图</a></td>
    <td><a href="./print_ass/">作业打印视图</a></td>
    {% if user.is_superuser %}  <td><a href="./rejudge/">重新判断</a></td> {% endif %}
  </tr>
</table>

{% endblock %}

templates/judge/judge_list.html
{% extends "base.html" %}

{% block content%}

<h2>判题结果</h2>

<table border = 1>
<tr>
	<td>判题编号</td> 
	<td>用 户</td>
	<td>姓  名</td>
	<td>问 题</td>
	<td>语 言</td>
	<td>判题结果</td>
	<td>提交时间</td>
</tr>
{% for judge in object_list %}

<tr>
  <td><a href="/judge/{{judge.id}}/"> {{judge.id}} </a> </td>
   <td><a href="/users/{{judge.user.id}}/"> {{judge.user}} {{judge.user.first_name}}</a> </td>
   <td><a href="/users/{{judge.user.id}}/"> {{judge.user.get_profile.name}} {{judge.user.first_name}}</a> </td>
   <td><a href="/problem/{{judge.problem.id}}/"> {{judge.problem.id}}</a></td>
   <td> {{judge.language}} </td>
   <td><a href="/judge/{{judge.id}}/"> {{judge.get_result_display}} </a> </td>
   <td> {{judge.submittime|date:"Y-m-j,G:i:s"}} </td>
</tr>

{% endfor %}
</table>
{% endblock %}


{% block navigator %}
{% if is_paginated %}
<table border = 1>
<tr>
   {% if has_previous %} <td><a href="./?{{previous}}">前一页</a></td>  {% endif %}
   <td>current:{{page}}/{{pages}}</td>
   {% if has_next %} <td><a href="./?{{next}}">后一页</a></td> {% endif %}
</tr>
</table>
{% endif %}
{% endblock %}

templates/judge/judge_print.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="zh-cn" />
        <meta name="keywords" content="online judge" />

        <title> 答题详细报告 - 编号{{object.id}}</title>

    </head>

    <body>

<h1> 答题详细报告 - 编号{{object.id}}</h1>

  <p>注册号：{{object.user.username}} </p>
  <p>姓名：{{object.user.first_name}}</p>
  <p>答题时间：{{object.submittime}}</p>
<h2>问题叙述</h2>
<p>问题标题：  {{object.problem.title}}</p>
<p>问题描述：</p>  <pre>{{object.problem.description}}</pre>
<p>输入要求</p><pre>{{object.problem.input}}</pre>
<p>输出要求</p><pre>{{object.problem.output}}</pre>
<p>输入实例</p><pre>{{object.problem.sampleinput}}</pre>
<p>输出实例</p><pre>{{object.problem.sampleoutput}}</pre>
<h2>解答内容</h2>
 <p>所用编程语言： {{object.get_language_display}}</p>
 <p>源代码</p>
 <pre>{{object.sourcecode|escape}}</pre></td>

<h2>判题结果</h2>
    <p>{{object.result}} - {{object.get_result_display}}</p>
    <p>判题结果补充说明</p>
       <pre>{{object.result_detail}}</pre>

    </body>
</html>

templates/judge/judge_print_ass.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="zh-cn" />
        <meta name="keywords" content="online judge" />

        <title> 作业 - 编号{{object.id}} - 题号{{object.problem.id}}</title>

    </head>

    <body>

<h1> 作业 - 编号:{{object.id}} - 题号:{{object.problem.id}}- 标题:{{object.problem.title}}</h1>

  <p>注册号：{{object.user.username}} </p>
  <p>姓名：{{userprofile.name}}</p>
  <p>班级：{{userprofile.classes}}</p>
  <p>答题时间：{{object.submittime|date:"Y-m-j,G:i:s"}}</p>
<h2>问题叙述</h2>
<p>问题编号：{{ object.problem.id }}</p>
<p>问题标题：  {{object.problem.title}}</p>
<h4>问题描述</h4>  {{object.problem.description}}</p>
<h4>输入要求</h4><p>{{object.problem.input}} </p>
<h4>输出要求</h4><p>{{object.problem.output}} </p>
<h4>输入实例</h4><pre>{{object.problem.sampleinput}}</pre>
<h4>输出实例</h4><pre>{{object.problem.sampleoutput}}</pre>
<h2>解答内容</h2>
 <p>所用编程语言： {{object.get_language_display}}</p>
 <p>源代码</p>
 <pre>{{object.sourcecode|escape}}</pre></td>

<h2>判题结果</h2>
    <p>{{object.result}} - {{object.get_result_display}}</p>
    <p>判题结果补充说明</p>
       <pre>{{object.result_detail}}</pre>

    </body>
</html>

templates/judge/judge_print_exp.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="zh-cn">
    <head>
        <meta http-equiv="Content-type" content="text/html; charset=utf-8" />
        <meta http-equiv="Content-Language" content="zh-cn" />
        <meta name="keywords" content="online judge" />

        <title> 实验 - 编号{{object.id}} - 题号{{object.problem.id}}</title>

    </head>

    <body>

<h1> 实验 - 编号:{{object.id}} - 题号:{{object.problem.id}}- 标题:{{object.problem.title}}</h1>

  <p>注册号：{{object.user.username}} </p>
  <p>姓名：{{userprofile.name}}</p>
  <p>班级：{{userprofile.classes}}</p>
  <p>答题时间：{{object.submittime|date:"Y-m-j,G:i:s"}}</p>
<h2>问题叙述</h2>
<p>问题编号：{{ object.problem.id }}</p>
<p>问题标题：  {{object.problem.title}}</p>
<h4>问题描述</h4>  {{object.problem.description}}</p>
<h4>输入要求</h4><p>{{object.problem.input}} </p>
<h4>输出要求</h4><p>{{object.problem.output}} </p>
<h4>输入实例</h4><pre>{{object.problem.sampleinput}}</pre>
<h4>输出实例</h4><pre>{{object.problem.sampleoutput}}</pre>
<h2>解答内容</h2>
 <p>所用编程语言： {{object.get_language_display}}</p>
 <p>源代码</p>
 <pre>{{object.sourcecode|escape}}</pre></td>

<h2>判题结果</h2>
    <p>{{object.result}} - {{object.get_result_display}}</p>
    <p>判题结果补充说明</p>
       <pre>{{object.result_detail}}</pre>
    </body>
</html>